services:
  api:
    build: ./backend
    ports:
      - "3000:3000"
  web:
    build:
      context: ./frontend
      args:
        VITE_API_URL: "http://localhost:3000"
    ports:
      - "8080:80"
    depends_on:
      - api
